# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzg-yE9rxaLw3j2N-2jikOnKS_2SIO0w
"""

import requests

# 目標網址 (台灣銀行匯率 CSV 資料)
url = 'https://rate.bot.com.tw/xrt/flcsv/0/day'

# 發送 GET 請求並取得匯率資料
rate = requests.get(url)
rate.encoding = 'utf-8'  # 設置編碼避免亂碼

# 解析回傳資料
rts = rate.text.split('\n')  # 依換行符號分割成多行

# 資料處理與輸出
for i in rts:
    try:
        # 以逗號分割每行資料
        a = i.split(',')

        # 確認資料行長度，避免索引錯誤
        if len(a) > 12 and a[0]:
            print(a[0] + ' : ' + a[12])  # 輸出貨幣代號和匯率
    except Exception as e:
        # 顯示錯誤訊息並繼續執行
        print(f'解析錯誤: {i}, 錯誤訊息: {e}')

